### PR TITLE
NXP-32235: update functional test for coldstorage

### PR DESCRIPTION
**Pull request by Nishant0928**
https://jira.nuxeo.com/browse/NXP-32235

### CODE REVIEW

**Review by Pranit-Sotre — DISMISSED** [review]

**Review by MansaQA — DISMISSED** [review]

**Review by arupmmi07 — DISMISSED** [review]

**Comment by guirenard** [comment]
Again as a reminder, functional test executions is disabled in our CI since https://github.com/nuxeo/nuxeo-coldstorage/commit/d618155bd28655181c7023910659d8a833395192 

I am not sure I understand the purpose of pushing the update of ftests without re-enabling their execution ...

**Comment by guirenard** [comment]
BTW, linked https://jira.nuxeo.com/browse/NXP-32235 has a bad component field and is missing fix versions

**Comment by Nishant0928** [comment]
> BTW, linked https://jira.nuxeo.com/browse/NXP-32235 has a bad component field and is missing fix versions

yeah , changed it .

**Comment by rahuljain-dev** [comment]
> Again as a reminder, functional test executions is disabled in our CI since [d618155](https://github.com/nuxeo/nuxeo-coldstorage/commit/d618155bd28655181c7023910659d8a833395192)
> 
> I am not sure I understand the purpose of pushing the update of ftests without re-enabling their execution ...

addons ftests will be run on top of Nuxeo WEBUI, once we generate rc with node18 upgrade, you can also enable the functional test in pipeline, this code will help in addon CI, so that when your CI run it won't break.

**Review by rahuljain-dev — APPROVED** [review]

**Review by MansaQA — APPROVED** [review]

**Review by arupmmi07 — APPROVED** [review]
ok, verified

**Pull request merged**
